source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SpriteWidget_Example', :exclusive => true do
  pod "SpriteWidget", :path => "../"
end

target 'SpriteWidget_Tests', :exclusive => true do
  pod "SpriteWidget", :path => "../"

  
end
